export const cuisineList = [
    "Món Hàn",
    "Đồ nướng",
    "Bữa sáng",
    "Burgers",
    "Cafe",
    "Món Trung",
    "Tráng miệng",
    "Món Pháp",
    "Món Việt",
    "Món chay",
    "Cơm",
    "Món Ý",
    "Món Nhật",
    "Đồ cuốn",
    "Mì",
    "Phở",
    "Xôi",
    "Pizza",
    "Salads",
    "Hải sản",
    "Bánh mì",
    "Steak",
    "Sushi",
    "Hoa quả",
    "Kem",
    "Bún",
  ];